// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {soundcloud} from '../models';
import {main} from '../models';

export function CancelMatching(arg1:string):Promise<void>;

export function CreateSoundCloudPlaylist(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<soundcloud.CreatedPlaylist>;

export function GetMatches(arg1:string):Promise<Record<string, main.TracksWrapper>>;

export function RefreshAuthState():Promise<void>;

export function ScoredTrackBind():Promise<main.ScoredTrack>;

export function SoundCloudAuthUrl():Promise<string>;

export function SpotifyAuthUrl():Promise<string>;

export function SpotifyPlaylist(arg1:string):Promise<main.PlaylistWithTracks>;

export function SpotifyPlaylists():Promise<Array<main.Playlist>>;

export function TracksWrapperBind():Promise<main.TracksWrapper>;
