// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spotify} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RefreshAuthState():Promise<void>;

export function SoundCloudAuthUrl():Promise<string>;

export function SpotifyAuthUrl():Promise<string>;

export function SpotifyPlaylists():Promise<Array<spotify.SimplePlaylist>>;
