// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMatching(arg1) {
  return window['go']['main']['App']['CancelMatching'](arg1);
}

export function CreateSoundCloudPlaylist(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSoundCloudPlaylist'](arg1, arg2, arg3, arg4);
}

export function GetMatches(arg1) {
  return window['go']['main']['App']['GetMatches'](arg1);
}

export function GetStreams(arg1) {
  return window['go']['main']['App']['GetStreams'](arg1);
}

export function RefreshAuthState() {
  return window['go']['main']['App']['RefreshAuthState']();
}

export function ScoredTrackBind() {
  return window['go']['main']['App']['ScoredTrackBind']();
}

export function SoundCloudAuthUrl() {
  return window['go']['main']['App']['SoundCloudAuthUrl']();
}

export function SpotifyAuthUrl() {
  return window['go']['main']['App']['SpotifyAuthUrl']();
}

export function SpotifyPlaylist(arg1) {
  return window['go']['main']['App']['SpotifyPlaylist'](arg1);
}

export function SpotifyPlaylists() {
  return window['go']['main']['App']['SpotifyPlaylists']();
}

export function TracksWrapperBind() {
  return window['go']['main']['App']['TracksWrapperBind']();
}
